POST http://localhost:8080/api/v1/segments/create
Content-Type: application/json
Authorization: Bearer tutbudettoken

{
  "slug": "AVITO_DISCOUNT_50"
}

###
DELETE http://localhost:8080/api/v1/segments/delete
Content-Type: application/json
Authorization: Bearer tutbudettoken

{
  "slug": "AVITO_DISCOUNT_50"
}

###
POST http://localhost:8080/api/v1/users/segments
Content-Type: application/json
Authorization: Bearer tutbudettoken

{
  "user_id": "b2c03a4c-4409-11ee-be56-0242ac120002",
  "segments_add": [
    "AVITO_VOICE_MESSAGES",
    "AVITO_PERFORMANCE_VAS",
    "AVITO_DISCOUNT_50"
  ],
  "segments_del": [
    "AVITO_DISCOUNT_30"
  ]
}

###
GET http://localhost:8080/api/v1/users/active-segments?user_id=b2c03a4c-4409-11ee-be56-0242ac120002
Accept: application/json
Authorization: Bearer tutbudettoken

###