POST http://localhost:8080/api/v1/segments/create
Content-Type: application/json
Authorization: Bearer 73068b821f36d1511d6eb0f1a66caafa35bd23ef7294b6eee7ff3eae06a959c1

{
  "slug": "AVITO_DISCOUNT_30"
}

###
POST http://localhost:8080/api/v1/segments/create
Content-Type: application/json
Authorization: Bearer 73068b821f36d1511d6eb0f1a66caafa35bd23ef7294b6eee7ff3eae06a959c1

{
  "slug": "AVITO_DISCOUNT_AUTO",
  "percentageUsers": 8000
}

###
DELETE http://localhost:8080/api/v1/segments/delete
Content-Type: application/json
Authorization: Bearer 73068b821f36d1511d6eb0f1a66caafa35bd23ef7294b6eee7ff3eae06a959c1

{
  "slug": "AVITO_DISCOUNT_AUTO"
}

###
POST http://localhost:8080/api/v1/users/segments
Content-Type: application/json
Authorization: Bearer 73068b821f36d1511d6eb0f1a66caafa35bd23ef7294b6eee7ff3eae06a959c1

{
  "user_id": "b2c03a4c-4409-11ee-be56-0242ac120011",
  "segments_add": [
  ],
  "segments_del": [
  ]
}

###
GET http://localhost:8080/api/v1/users/active-segments?user_id=b2c03a4c-4409-11ee-be56-0242ac120002
Accept: application/json
Authorization: Bearer 73068b821f36d1511d6eb0f1a66caafa35bd23ef7294b6eee7ff3eae06a959c1

###